.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PROBLECTIX 1 "May 30, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
problectix \- Vorschau einer Aufgabensammlung
.SH SYNOPSIS
.B problectix
.RI [ options ] 
.br
.SH DESCRIPTION
.B problectix
.br
Erzeugt einen Verzeichnisbaum mit Bildern im *.png-Format aus Aufgaben im *.tex-Format. 
.PP
.SH OPTIONS
.B problectix
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.PP
.B -h, --help
.br
Kurzübersicht über Optionen
.PP
.B -v, --verbose
.br
Sagt, was das Programm gerade macht (verbose)
.PP
.B -vv, --verbose --verbose
.br
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.PP
.B Vorschau-Aufgabensammlung erstellen
.PP
.B --browsetree
.br
Bearbeitet ALLE *.tex-Aufgaben, die nicht durch ignorierte
Verzeichnisse verborgen sind. Die Aufgabensammlungen werden erstellt
im Verzeichnis problectix-browsetree (konfigurierbar)
.PP
.B --browsetree --path /Pfad/zu/den/Aufgaben
.br
Zusatzangabe in welchem Verzeichnis nach *.tex-Dateien gesucht werden soll.
.PP
.B --browsetree --renew
.br
Löscht das Ausgabe-Verzeichnis problectix-browsetree, um es neu zu erzeugen. 
.br
ACHTUNG: vorherige Daten werden entfernt. Die neuerstellung ALLER
Aufgabe dauert lange.
.PP
.B Ignorierte Dateien
.PP
Problectix besitzt eingebaute Verzeichnisnamen, in denen NICHT nach
Aufgaben gesucht wird.

Zusätzlich können in der obersten Verzeichnisebene eines Projekts in
der Datei .problectix.ignore eigene Verzeichnisse ignoriert werden.

Alle ignorierten Verzeichnisse werden angezeigt mit:
.PP
.B --ignored-dirs
.PP
Genauere Angaben zu den ignorierten Verzeichnissen git es mit:
.PP
.B --count -vv
.PP
.B Quellcode Suche
.PP
Im Quellcode aller *.tex-Dateien des ganzen Projektverzeichisses kann
nach einem String gesucht werden mit:
.PP
.B --search <string>
.PP
.B Konfiguration
.PP
Systemweit in der Datei /etc/problectix/problectix.conf
.PP
.PP
Für den User in der Datei .problectix/problectix.conf
.PP
Ignorierte Dateien in einem Projekt in dessen wurzelverzeichnis
in der Datei .problectix.ignore
.TP
.SH SEE ALSO
.BR problectix-marklist (1),
.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "probectix-marklist -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
