#!/usr/bin/perl -w
# Dieses Script (examplix) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Bibliotheken
use strict;
use Getopt::Long;
use DBI;
use Spreadsheet::WriteExcel;



my $create="";
my $tasks="";
my $help=1;

my %hash=();

my @students=("rainer","werner","udo");


# Parsen der Optionen
my $testopt=GetOptions(
           "create|c=s" => \$create,
           "tasks|t=s" => \$tasks,
           "help|h" => \$help,
          );

# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);


# --create
if ($create ne "") {
  $help=0;
  #
  if (-e $create){
      print "ERROR: \n",
            "   Exam-Directory $create exists already\n",
            "   I'm doing nothing!\n";
  } else {
     &create_exam($create); 
  }
}


# --tasks
if ($tasks ne "") {
    $help=0;
    if (not -e "$tasks/exam.conf"){
	print "Exam $tasks does not exist. Use option --create\n";
        exit;
    }

    print "Creating the following Task-Files of exam $tasks:\n";

    %hash = &create_task_hash();
    
    while (my ($file,$prob) = each %hash ){
        print "$file with Problems: $prob \n";
        &create_file($file,$prob);
    }






# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
examplix (EXAMs Per LInux/uniX) is a tool to divide the correction of a larger exam into smaller chunks for a number of people and put together these chunks and calsulate a mark.  

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info
  -c  / --create examname
  -t  / --tasks examname

Please see the examplix(1) man pages for full documentation
');
   print "\n";
   exit;
}





exit;











my $row;
my $column;
my $data;
my $format;


my $excel = new Spreadsheet::WriteExcel( "$create/test.xls" );

my $sheet  = $excel -> addworksheet();


$row=1;
$column=2;
$data="hemp";
$format = $excel->add_format();
$format->set_align('center');
$format->set_bg_color('red');

$sheet -> write( $row, $column, $data, $format );


$excel -> close();






############################################################
# SUB
############################################################
sub create_file {
    my ($file,$prob) = @_;
    my @problems = split(/;/,$prob);
    my ($teacher,$subject,$numstring,$day)=split(/_/,$file);
    my $filepath=$tasks.'/tasks/'.$file;
    my $excel = new Spreadsheet::WriteExcel( "$filepath" );
    $excel->set_custom_color(40, 238,  160,  111  );

    my $color="grey";
    if ($numstring eq "Erstkorrektur"){
       $excel->set_custom_color(40, 236,  155,  155  );
       $color="red";
       $numstring="Erst."
    } elsif ($numstring eq "Zweitkorrektur") {
       $excel->set_custom_color(40, 135,  200,  135  );
       $color="green";
       $numstring="Zweit."
    }

    my $sheet  = $excel -> addworksheet();
    $sheet->protect('examplix');
    my $row=1;
    my $column=2;

    my $format = $excel->add_format();
    $format->set_align('left');
    $format->set_bg_color('grey');
    $format->set_border(1);

    my $format_red = $excel->add_format();
    $format_red->set_align('center');
    $format_red->set_bg_color($color);
    $format_red->set_border(1);

    # unlocked to add data
    my $format_empty = $excel->add_format(locked => 0);
    $format_empty->set_border(1);
    $format_empty->set_bg_color(40);


    # inserting the students
    $row=4;
    foreach my $student (@students){
       $sheet -> write( $row, 0, $student, $format );
       $row++;
    }


    # inserting the header
    $sheet -> write( 0, 0, $teacher, $format_red );
    $column=1;
    foreach my $pro (@problems){
       $sheet -> write( 3, $column, $pro, $format_red );
       $sheet -> write( 2, $column, $day, $format_red );
       $sheet -> write( 1, $column, $subject, $format_red );
       $sheet -> write( 0, $column, $numstring, $format_red );
       my $i;
       for ($i = 1; $i <= $#students+1; $i++) { 
          $sheet -> write( $i+3, $column, "", $format_empty );
       }
       $column++;
    }
    $excel -> close();
}





sub create_task_hash {
        my $tmp="";
        my $new_1="";
        my $new_2="";
        my %filename=();
    open (EXAM, "$tasks/exam.conf")|| die "Fehler: $!";
    while (<EXAM>){
        s/^ //g; # Leerzeichen am Zeilenangfang entfernen
        if(/^\#/){ # # am Anfang bedeutet Kommentarzeile
           next;
        } 
        chomp();
        my ($day,
            $problem,
            $subject,
            $factor,
            $corr_1,
            $group_1,
            $corr_2,
            $group_2)=split(/;/);

        if ($group_1 eq "") {
            $group_1="all";
        }
        if ($group_2 eq "") {
            $group_2="all";
        }
        my $filename_1="$corr_1"."_"."$subject"."_".
                       "Erstkorrektur"."_"."$day"."_"."$group_1".".xls";
        my $filename_2="$corr_2"."_"."$subject"."_".
                       "Zweitkorrektur"."_"."$day"."_"."$group_1".".xls";
        if (not exists $filename{$filename_1} ){
	    $filename{$filename_1}="$problem";
        } else {
            $tmp=$filename{$filename_1};
            $new_1=$tmp.";".$problem;
            $filename{$filename_1}="$new_1";
        }
        if (not exists $filename{$filename_2} ){
	    $filename{$filename_2}="$problem";
        } else {
            $tmp=$filename{$filename_2};
            $new_2=$tmp.";".$problem;
            $filename{$filename_2}="$new_2";
        }
    }
    close EXAM;
    return %filename;
}








}


sub create_exam {
    my ($exam) = @_;
     print " Creating a new exam $create\n";
     system("mkdir $create");
     system("mkdir $create/config");
     system("touch $create/exam.conf");
     open (EXAM, ">>$create/exam.conf")|| die "Fehler: $!";
     print EXAM "#TAG;AUFGABE;FACH;FAKTOR;KORR1;GROUP1;KORR2;GROUP2\n";
     close EXAM;
     system("mkdir $create/students");
     system("mkdir $create/teachers");
     system("mkdir $create/tasks");
     system("mkdir $create/collect");
     system("mkdir $create/results");
}


sub  check_options{
   my ($parse_ergebnis) = @_;
   if (not $parse_ergebnis==1){
      my @list = split(/\//,$0);
      my $scriptname = pop @list;
      print "\nYou have made a mistake, when specifying options.\n"; 
      print "See error message above. \n\n";
      print "... $scriptname is terminating.\n\n";
      exit;
   } else {
      print "All options  were recognized.\n";
   }

}


