#!/usr/bin/perl
# Dieses Script (convert2utf8) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use File::Basename qw( basename
                       dirname
                       fileparse
                     );       

my $help=0;
my $reverse=0;
my $dir="";
my $file="";

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "reverse|r" => \$reverse,
           "dir|d=s" => \$dir,
           "file|f=s" => \$file,
          );




&check_options($testopt);

############################################################
# Start
############################################################

# --help
if ($help==1 or ($dir eq "" and $file eq "")){
   print "\nconvert2utf8 converts a file from ISO 8859-1 to utf8 \n",
         "             or vice versa.";

   # optionen
   print('

Options:

  -h  / --help
  -f | --file /absolute/path/to/file
  -d | --dir  /absolute/path/to/dir
  -r | --reverse  (convert from utf8 to ISO 8859-1)

');
   exit;
}



# --dir
if ($dir ne "" and -d $dir){
    print "Converting $dir:\n";
    opendir DIR, $dir or return;
    foreach my $datei (readdir DIR){
        if ($datei eq "."){next};
        if ($datei eq ".."){next};
        if ($datei=~/temp.tex$/ or $datei=~/temp-[0-9]+.tex$/){
            print "   Skipping temporary file $datei\n";
            next;
        }
        if ($datei=~/.tex$/){
            &convert($datei);
        }
    }
    close DIR;
    exit;
}




# --file
if ($file ne "" and -f $file){
    print "Converting $file:\n";
    &convert($file);
    exit;
}




############################################################
# Subs
############################################################

sub  check_options{
   my ($parse_ergebnis) = @_;
   if (not $parse_ergebnis==1){
      my @list = split(/\//,$0);
      my $scriptname = pop @list;
      print "\nSie haben bei der Eingabe der ",
            "Optionen einen Fehler begangen.\n"; 
      print "Siehe Fehlermeldung weiter oben. \n\n";
      print "... $scriptname beendet sich.\n\n";
      exit;
   } else {
         print "Alle Befehls-Optionen wurden erkannt.\n\n";
   }

}

sub convert {
    my ($file_local)=@_;
    my $file_abs;
    if ($file ne ""){
        $file_abs=$file_local;
    } elsif ($dir ne ""){
        $file_abs=$dir."/".$file_local;
    }

    my $tmp="/tmp/tmp.tex";
    print "* Converting file:\n  $file_abs\n";
    if ($reverse==0){
        system("iconv -f 8859_1 -t utf-8 $file_abs -o $tmp");
    } else {
        system("iconv -f utf-8 -t 8859_1 $file_abs -o $tmp");
    }
    system("mv $tmp $file_abs");
}
