#!/usr/bin/perl

# This script copies examples from the problectix package in the users 
# directory $HOME/problectix-test runs them through latex and dvips
#
# This is used to check if the all the formatting is still correct,
# i.e. after a change in the *.cls and *.dtx - files 

$home=$ENV{'HOME'};

$testdir="$home"."/problectix-test";

print $testdir,"\n";

# make sure, that problectix-test exists
if (-e "$testdir"){
    print "\n $testdir exists. Please delete it manually \n\n";
    exit;
} else {
    print "Creating $testdir \n"; 
    system("mkdir $testdir");   
}

# copy the examples
system("cp /usr/share/texmf/doc/latex/problectix/examples/aufgaben/* $testdir");

# copy all the test-scripts
system("cp /usr/share/texmf/doc/latex/problectix/examples/test/* $testdir");



# All the *.tex-files in this list will be run through latex/dvips/pdflatex
# 
@filelist=("alles-kamulti",
	   "schueler-ka",
	   "schueler-ka-notenliste",
	   "schueler-kamulti",
	   "schueler-kamulti-notenliste",
	   "schueler-kamulti-notenliste-bszleo",
	   "schueler-kamulti-1.5",
	   "schueler-kamulti-0.8",
	   "lsg-kamulti",
	   "schueler-pruefung",
	   "schueler-pruefung-arial",
	   "schueler-arb",
	   "schueler-arb-bszleo",
	   "schueler-bszleoexam",
	   "schueler-bszleoexam-arial",
	   "notenliste",
	   );

# latex all the test-scripts 

foreach $file (@filelist) {
    # create *.ps
    $command="cd $testdir; latex $file.tex";
    print "latex: "."$command"."\n";
    system("$command");
    system("$command");
    $command2="cd $testdir; dvips $file.dvi";
    print "dvips: "."$command2"."\n";
    system("$command2");
    # create *.pdf   
    $command3="cd $testdir; pdflatex $file.tex";
    print "pdflatex: "."$command3"."\n";
    system("$command3");
    # cleaning up
    $command4="cd $testdir; rm $file.aux; rm $file.log; rm $file.tex; rm $file.dvi;";
    print "Cleanung: "."$command4"."\n";
    system("$command4");
}



# remove the aufgaben
    system("cd $testdir; rm aufgabe*");
