Document: problectix
Title: Debian problectix Manual
Author: <insert document author here>
Abstract: This manual describes what problectix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/problectix/problectix.sgml.gz

Format: postscript
Files: /usr/share/doc/problectix/problectix.ps.gz

Format: text
Files: /usr/share/doc/problectix/problectix.text.gz

Format: HTML
Index: /usr/share/doc/problectix/html/index.html
Files: /usr/share/doc/problectix/html/*.html

  
